language: php
php:
  - 7.0
  - 7.1
  - 7.2

install:
  - composer install

script:
  - mkdir -p build/logs
  - cd tests
  - phpunit --coverage-clover=../build/logs/clover.xml .
  - cd ../

after_script:
  - php vendor/bin/coveralls -v
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
