language: php
php:
  - 7.1
  - 7.2

install:
  - composer install

script:
  - phpunit

after_script:
#  - php vendor/bin/coveralls -v
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./logs/clover.xml
